# Generated by Django 5.2 on 2025-04-29 18:18

from django.db import migrations


def create_default_roles(apps, schema_editor):
    UserRole = apps.get_model('pharmacy', 'UserRole')
    
    default_roles = [
        {
            'name': 'admin',
            'permissions': 'all',
            'description': 'Full system access with all permissions'
        },
        {
            'name': 'pharmacist',
            'permissions': 'view_medicine,add_medicine,change_medicine,delete_medicine,view_prescription',
            'description': 'Manages medicines and prescriptions'
        },
        {
            'name': 'cashier',
            'permissions': 'view_medicine,view_sale,add_sale',
            'description': 'Handles sales and transactions'
        },
        {
            'name': 'inventory',
            'permissions': 'view_medicine,change_medicine,view_supplier,add_supplier,change_supplier',
            'description': 'Manages inventory and suppliers'
        }
    ]
    
    for role_data in default_roles:
        UserRole.objects.create(**role_data)

def remove_default_roles(apps, schema_editor):
    UserRole = apps.get_model('pharmacy', 'UserRole')
    UserRole.objects.filter(name__in=['admin', 'pharmacist', 'cashier', 'inventory']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_userrole_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, remove_default_roles),
    ]
