# Generated by Django 5.2 on 2025-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_create_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
